# Generated by Django 5.2.4 on 2025-07-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message_body",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="sent_at",
            new_name="timestamp",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="message_body",
            new_name="content",
        ),
    ]
