# Generated by Django 5.2.4 on 2025-08-01 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_rename_message_body_message_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MessageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_content", models.TextField()),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edited_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Edit History",
                "verbose_name_plural": "Message Edit History",
                "ordering": ["-edited_at"],
            },
        ),
    ]
