# Generated by Django 5.2.4 on 2025-08-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_message_edited_message_edited_at_messagehistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="messaging.message",
            ),
        ),
    ]
