# Generated by Django 5.2.4 on 2025-07-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Unique username for login", max_length=150, unique=True
            ),
        ),
    ]
