# Generated by Django 5.2.4 on 2025-07-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                help_text="Role of the user in the application",
                max_length=20,
            ),
        ),
    ]
